// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6lihpjU7i1l9-rO1iV4-CyCP7bEWLJZ0',
    appId: '1:784526488308:web:288956a5290b5503f9e4a1',
    messagingSenderId: '784526488308',
    projectId: 'feedcards',
    authDomain: 'feedcards.firebaseapp.com',
    storageBucket: 'feedcards.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSXftbuEJj3p7pNC4Hmr10r8pydPtd-Zo',
    appId: '1:784526488308:android:491ba005ab17f856f9e4a1',
    messagingSenderId: '784526488308',
    projectId: 'feedcards',
    storageBucket: 'feedcards.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8UjXZm7wTugfO13oDDiv-uRpohuHm8Rw',
    appId: '1:784526488308:ios:d902fc2c6d48c551f9e4a1',
    messagingSenderId: '784526488308',
    projectId: 'feedcards',
    storageBucket: 'feedcards.appspot.com',
    iosBundleId: 'com.example.feedcards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8UjXZm7wTugfO13oDDiv-uRpohuHm8Rw',
    appId: '1:784526488308:ios:d902fc2c6d48c551f9e4a1',
    messagingSenderId: '784526488308',
    projectId: 'feedcards',
    storageBucket: 'feedcards.appspot.com',
    iosBundleId: 'com.example.feedcards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6lihpjU7i1l9-rO1iV4-CyCP7bEWLJZ0',
    appId: '1:784526488308:web:6280bc96c7db0963f9e4a1',
    messagingSenderId: '784526488308',
    projectId: 'feedcards',
    authDomain: 'feedcards.firebaseapp.com',
    storageBucket: 'feedcards.appspot.com',
  );
}
